#
###################################
# Site wide configuration
####################################
#
title: Arnab Bhadury
email: arnabhy@gmail.com
description: Random thoughts
url:


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Vancouver
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Arnab Bhadury 
  avatar: logo.png
  job: "Topics and recommender systems @ Flipboard"
  bio: "ML Engineer in Vancouver, ML meetups co-organizer"
  email: "abhadury@flipboard.com"
  disqus-shortname:
  twitter: "ArnieB0426"
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: arnie0426
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
